routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');


Route::middleware('guest')->group(function () {

    Route::get('login', function () {
        return view('login');
    })->name('login');

    Route::post('login', [\App\Http\Controllers\LoginController::class, 'authenticate'])->name('login.authenticate');

});

Route::middleware('auth')->group(function () {
    Route::post('logout', [\App\Http\Controllers\LoginController::class, 'destroy'])->name('logout');
});

Route::get('categories/{slug}', [\App\Http\Controllers\CategoryController::class, 'show'])->name('article.index');

Route::get('articles/{article}', [\App\Http\Controllers\ArticleController::class, 'show'])->name('article.show');

Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::middleware('author')->group(function () {
        Route::get('dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        Route::prefix('articles')->name('article.')->group(function () {
            Route::get('', [\App\Http\Controllers\ArticleController::class, 'index'])->name('index');
            Route::get('create', [\App\Http\Controllers\ArticleController::class, 'create'])->name('create');
            Route::get('get-articles', [\App\Http\Controllers\ArticleController::class, 'getArticles'])->name('get-articles');
            Route::get('{article}/edit', [\App\Http\Controllers\ArticleController::class, 'edit'])->name('edit');
            Route::post('', [\App\Http\Controllers\ArticleController::class, 'store'])->name('store');
            Route::post('{article}/update', [\App\Http\Controllers\ArticleController::class, 'update'])->name('update');
            Route::post('{article}/destroy', [\App\Http\Controllers\ArticleController::class, 'destroy'])->name('destroy');
        });
    });

    Route::middleware('admin')->group(function () {
        Route::prefix('users')->name('user.')->group(function () {
            Route::get('', [\App\Http\Controllers\UserController::class, 'index'])->name('index');
            Route::get('create', [\App\Http\Controllers\UserController::class, 'create'])->name('create');
            Route::get('get-users', [\App\Http\Controllers\UserController::class, 'getUsers'])->name('get-users');
            Route::post('', [\App\Http\Controllers\UserController::class, 'store'])->name('store');
        });
    });
});

Route::prefix('profiles')->middleware(['auth', 'owner'])->name('profile.')->group(function () {
    Route::get('{user}', [\App\Http\Controllers\ProfileController::class, 'show'])->name('show');
    Route::post('{user}/update-profile-data', [\App\Http\Controllers\ProfileController::class, 'updateProfileData'])->name('update-profile-data');
    Route::post('{user}/update-profile-image', [\App\Http\Controllers\ProfileController::class, 'updateProfileImage'])->name('update-profile-image');
    Route::post('{user}/delete-profile-image', [\App\Http\Controllers\ProfileController::class, 'deleteProfileImage'])->name('delete-profile-image');
    Route::post('{user}/change-password', [\App\Http\Controllers\ProfileController::class, 'changePassword'])->name('change-password');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Article extends Model
{
    use HasFactory;

    protected $fillable = [
        'category_id',
        'cover_image',
        'title',
        'content',
        'is_locked',
        'user_id'
    ];

    public function author() : BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\Category;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('admin.article.index');
    }

    public function getArticles() : JsonResponse
    {
        $draw = request()->input('draw');
        $start = request()->input('start');
        $length = request()->input('length');
        $searchValue = request()->input('search.value');
        $orderColumn = request()->input('order.0.column');
        $orderDir = request()->input('order.0.dir');

        $columns = [
            0 => 'articles.title',
            1 => 'categories.name',
            2 => 'articles.is_locked',
            3 => 'users.name'
            // add more columns here...
        ];


        $query = Article::query()
            ->leftJoin('categories', 'categories.id', '=', 'articles.category_id')
            ->leftJoin('users', 'users.id', '=', 'articles.user_id')
            ->select(['articles.id', 'articles.title', 'articles.is_locked', 'categories.name', \DB::raw('users.name AS author')]);

        if (!empty($searchValue)) {
            $query->where(function ($q) use ($searchValue) {
                $q->where('articles.title', 'LIKE', "%$searchValue%")
                    ->orWhere('categories.name', 'LIKE', "%$searchValue%")
                    ->orWhere('users.name', 'LIKE', "%$searchValue%");
            });
        }

        if ($orderColumn != null) {
            $query->orderBy($columns[$orderColumn], $orderDir);
        }

        $totalCount = $query->count();
        $query->skip($start)->take($length);
        $data = $query->get();

        return response()->json([
            'draw' => $draw,
            'recordsTotal' => $totalCount,
            'recordsFiltered' => $totalCount,
            'data' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::where('category_parent_id', null)->get();

        foreach ($categories as $category) {
            $category->children = Category::where('category_parent_id', $category->id)->get();
        }

        return view('admin.article.create', [
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request) : JsonResponse
    {
        $validated = $request->validate([
            'category_id' => ['required', 'exists:categories,id'],
            'cover_image' => ['sometimes', 'image'],
            'title' => ['required'],
            'content' => ['required'],
            'is_locked' => ['required']
        ]);

        $url = null;

        if ($request->hasFile('cover_image')) {
            $file = $request->file('cover_image');
            $extension = $file->getClientOriginalExtension();
            $filename = uniqid('cover-image').'.'.$extension;
            $file->move(public_path('attachments/cover-images'), $filename);
            $url = 'attachments/cover-images/'.$filename;
        }

        $article = new Article();
        $article->category_id = $validated['category_id'];
        $article->cover_image = $url;
        $article->title = $validated['title'];
        $article->content = htmlspecialchars($validated['content']);
        $article->is_locked = $validated['is_locked'];
        $article->user_id = \Auth::id();
        $article->save();

        return response()->json([
            'message' => 'Success! The data has been created successfully'
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(Article $article)
    {
        $user = User::find($article->user_id)->select(['name', 'email'])->first();
        $article->user = $user;
        $article->content = htmlspecialchars_decode($article->content);

        if ($article->is_locked) {
            $count = 0;
            $index = 0;

            while ($count < 3) {
                $index = strpos($article->content, "</p>", $index + 1);
                if ($index === false) {
                    break;
                }
                $count++;
            }

            if ($count === 3) {
                $article->content = substr($article->content, 0, $index + 4); // Include "</p>" in the final string
            }
        }

        return view('article.show', [
            'article' => $article
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Article $article)
    {
        $categories = Category::where('category_parent_id', null)->get();

        foreach ($categories as $category) {
            $category->children = Category::where('category_parent_id', $category->id)->get();
        }

        return view('admin.article.edit', [
            'article' => $article,
            'categories' => $categories
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Article $article) : JsonResponse
    {
        $validated = $request->validate([
            'category_id' => ['required', 'exists:categories,id'],
            'cover_image' => ['sometimes', 'image'],
            'title' => ['required'],
            'content' => ['required'],
            'is_locked' => ['required']
        ]);

        $url = null;

        if ($request->hasFile('cover_image')) {
            $file = $request->file('cover_image');
            $extension = $file->getClientOriginalExtension();
            $filename = uniqid('cover-image').'.'.$extension;
            $file->move(public_path('attachments/cover-images'), $filename);
            $url = 'attachments/cover-images/'.$filename;

            if ($article->cover_image != null && File::exists(public_path($article->cover_image))) {
                File::delete(public_path($article->cover_image));
            }

            $article->cover_image = $url;
        }

        $article->category_id = $validated['category_id'];
        $article->title = $validated['title'];
        $article->content = htmlspecialchars($validated['content']);
        $article->is_locked = $validated['is_locked'];
        $article->save();

        return response()->json([
            'message' => 'Success! The data has been updated successfully'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Article $article)
    {
        if ($article->cover_image != null && File::exists(public_path($article->cover_image))) {
            File::delete(public_path($article->cover_image));
        }

        $article->delete();

        return response()->json([
            'message' => "Success! The data has been deleted successfully"
        ]);
    }
}

resources/views/admin/article/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="pagetitle">
        <h1>Artikel</h1>
    </div><!-- End Page Title -->
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Menulis Artikel</h5>

            <!-- General Form Elements -->
            <form id="create-article-form">
                @csrf
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label" for="category_id">Kategori</label>
                    <div class="col-sm-10">
                        <select class="form-select" aria-label="Default select example" name="category_id" id="category_id">
                            <option value="" selected disabled>Silakan Pilih Kategori</option>
                            @foreach($categories as $parent)
                                <optgroup label="{{ $parent->name }}">
                                    @foreach($parent->children as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </optgroup>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="cover_image" class="col-sm-2 col-form-label">Gambar Sampul</label>
                    <div class="col-sm-10">
                        <input class="form-control" type="file" id="cover_image" name="cover_image">
                        <div id="imagePreview" class="mt-3 d-none border" style="max-width: 400px"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="title" class="col-sm-2 col-form-label">Judul Artikel</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="content" class="col-sm-2 col-form-label">Isi Artikel</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" rows="12" id="content" name="content"></textarea>
                    </div>
                </div>

                <fieldset class="row mb-3">
                    <legend class="col-form-label col-sm-2 pt-0">Artikel</legend>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_locked" id="is_locked1" value="1" checked>
                            <label class="form-check-label" for="is_locked1">
                                Lock (hanya untuk member)
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_locked" id="is_locked2" value="0">
                            <label class="form-check-label" for="is_locked2">
                                Unlock (siapapun bisa membacanya)
                            </label>
                        </div>
                    </div>
                </fieldset>

                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Submit Button</label>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit Form</button>
                    </div>
                </div>

            </form><!-- End General Form Elements -->

        </div>
    </div>
@endsection

@push('customjs')
    <script>
        ClassicEditor
            .create( document.querySelector('#content'), {
                toolbar: [ 'undo', 'redo', 'bold', 'italic', 'numberedList', 'bulletedList' ]
            })

        function previewImage(event) {
            var imageInput = event.target;
            var imagePreview = document.getElementById('imagePreview');

            if (imageInput.files && imageInput.files[0]) {
                var reader = new FileReader();


                reader.onload = function (e) {
                    imagePreview.classList.remove('d-none')
                    imagePreview.innerHTML = '<img alt="Image Preview" class="img-fluid" src="' + e.target.result + '">';
                };

                reader.readAsDataURL(imageInput.files[0]);
            } else {
                imagePreview.innerHTML = '';
            }
        }

        $('#create-article-form [name="cover_image"]').on('change', function (e) {
            previewImage(e);
        })

        $('#create-article-form').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                url : '{{ route('admin.article.store') }}',
                type : 'POST',
                data : new FormData(this),
                processData : false,
                contentType : false,
                headers : {
                    'X-CSRF-TOKEN' : '{{ csrf_token() }}'
                },
                success : function (response) {
                    Swal.fire({
                        icon : 'success',
                        title : 'Success',
                        text : response.message,
                        timer : 3000,
                        timerProgressBar: true,
                        onAfterClose : function () {
                            location.reload();
                        }
                    })
                },
                error : function (xhr, status, error) {
                    if (xhr.status === 422) {
                        let errors = xhr.responseJSON.errors;
                        $('#create-article-form :input').each(function () {
                            $(this).parent().children('div.invalid-feedback').remove();
                            $(this).removeClass('is-invalid');
                            if (errors.hasOwnProperty($(this).attr('name'))) {
                                let errorMessage = document.createElement('div');
                                errorMessage.classList.add('invalid-feedback');
                                errorMessage.innerHTML = errors[$(this).attr('name')];
                                $(this).parent().append(errorMessage);
                                $(this).addClass('is-invalid');
                            }
                        })
                    }
                    Toast.fire({
                        icon : "error",
                        title : error
                    })
                }
            })
        })
    </script>
@endpush

resources/views/admin/article/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="pagetitle">
        <h1>Artikel</h1>
    </div><!-- End Page Title -->
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Sunting Artikel</h5>

            <!-- General Form Elements -->
            <form id="edit-article-form">
                @csrf
                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label" for="category_id">Kategori</label>
                    <div class="col-sm-10">
                        <select class="form-select" aria-label="Default select example" name="category_id" id="category_id">
                            <option value="" {{ $article->category_id == null ? 'selected' : '' }} disabled>Silakan Pilih Kategori</option>
                            @foreach($categories as $parent)
                                <optgroup label="{{ $parent->name }}">
                                    @foreach($parent->children as $category)
                                        <option value="{{ $category->id }}" {{ $article->category_id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                                    @endforeach
                                </optgroup>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="cover_image" class="col-sm-2 col-form-label">Gambar Sampul</label>
                    <div class="col-sm-10">
                        <input class="form-control" type="file" id="cover_image" name="cover_image">
                        <div id="imagePreview" class="mt-3 d-none border" style="max-width: 400px"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="title" class="col-sm-2 col-form-label">Judul Artikel</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="title" name="title" value="{{ $article->title }}">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="content" class="col-sm-2 col-form-label">Isi Artikel</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" rows="12" id="content" name="content">{!! $article->content  !!} </textarea>
                    </div>
                </div>

                <fieldset class="row mb-3">
                    <legend class="col-form-label col-sm-2 pt-0">Artikel</legend>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_locked" id="is_locked1" value="1" {{ $article->is_locked == 1 ? 'checked' : ''}}>
                            <label class="form-check-label" for="is_locked1">
                                Lock (hanya untuk member)
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="is_locked" id="is_locked2" value="0" {{ $article->is_locked == 0 ? 'checked' : ''}}>
                            <label class="form-check-label" for="is_locked2">
                                Unlock (siapapun bisa membacanya)
                            </label>
                        </div>
                    </div>
                </fieldset>

                <div class="row mb-3">
                    <label class="col-sm-2 col-form-label">Action Button</label>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                        <button type="button" class="btn btn-danger" id="delete-data-button">Delete Article</button>
                    </div>
                </div>

            </form><!-- End General Form Elements -->

        </div>
    </div>
@endsection

@push('customjs')
    <script>
        ClassicEditor
            .create( document.querySelector('#content'), {
                toolbar: [ 'undo', 'redo', 'bold', 'italic', 'numberedList', 'bulletedList' ]
            })

        function previewImage(event) {
            var imageInput = event.target;
            var imagePreview = document.getElementById('imagePreview');

            if (imageInput.files && imageInput.files[0]) {
                var reader = new FileReader();


                reader.onload = function (e) {
                    imagePreview.classList.remove('d-none')
                    imagePreview.innerHTML = '<img alt="Image Preview" class="img-fluid" src="' + e.target.result + '">';
                };

                reader.readAsDataURL(imageInput.files[0]);
            } else {
                imagePreview.innerHTML = '';
            }
        }

        $('#edit-article-form [name="cover_image"]').on('change', function (e) {
            previewImage(e);
        })

        $(document).ready(function () {
            var imagePreview = document.getElementById('imagePreview');
            imagePreview.classList.remove('d-none')
            imagePreview.innerHTML = '<img alt="Image Preview" class="img-fluid" src="' + '{{ asset($article->cover_image) }}' + '">';
        })

        $('#edit-article-form').on('submit', function (e) {
            e.preventDefault();

            let url = '{{ route('admin.article.update', ['article' => '%%id%%']) }}'
            url = url.replace('%%id%%', {{ $article->id }})

            $.ajax({
                url : url,
                type : 'POST',
                data : new FormData(this),
                processData : false,
                contentType : false,
                headers : {
                    'X-CSRF-TOKEN' : '{{ csrf_token() }}'
                },
                success : function (response) {
                    Swal.fire({
                        icon : 'success',
                        title : 'Success',
                        text : response.message,
                        timer : 3000,
                        timerProgressBar: true,
                        onAfterClose : function () {
                            location.reload();
                        }
                    })
                },
                error : function (xhr, status, error) {
                    if (xhr.status === 422) {
                        let errors = xhr.responseJSON.errors;
                        $('#edit-article-form :input').each(function () {
                            $(this).parent().children('div.invalid-feedback').remove();
                            $(this).removeClass('is-invalid');
                            if (errors.hasOwnProperty($(this).attr('name'))) {
                                let errorMessage = document.createElement('div');
                                errorMessage.classList.add('invalid-feedback');
                                errorMessage.innerHTML = errors[$(this).attr('name')];
                                $(this).parent().append(errorMessage);
                                $(this).addClass('is-invalid');
                            }
                        })
                    }
                    Toast.fire({
                        icon : "error",
                        title : error
                    })
                }
            })
        })

        $('#delete-data-button').on('click', function (e) {
            Swal.fire({
                icon : 'warning',
                title : "Confirmation",
                text : "Are you sure to delete this data?",
                showCancelButton: true,
                confirmButtonText: 'Delete',
                confirmButtonColor: '#dc3545'
            }).then( (result) => {
                if (result.isConfirmed) {
                    let url = '{{ route('admin.article.destroy', ['article' => '%%id%%']) }}'
                    url = url.replace('%%id%%', {{ $article->id }})
                    $.ajax({
                        url : url,
                        type : "POST",
                        headers : {
                            'X-CSRF-TOKEN' : '{{ csrf_token() }}'
                        },
                        success : function (response) {
                            Swal.fire({
                                icon : 'success',
                                title : 'Success',
                                text : response.message,
                                timer : 3000,
                                timerProgressBar: true,
                                onAfterClose : function () {
                                    window.location = '{{ route('admin.article.index') }}'
                                }
                            })
                        },
                        error : function (xhr, status, error) {
                            Toast.fire({
                                icon : 'error',
                                title : error
                            })
                        }
                    })
                }
            })
        })
    </script>
@endpush

resources/views/admin/article/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="pagetitle">
        <h1>Artikel</h1>
    </div><!-- End Page Title -->
    <div class="card">
        <div class="card-body" style="overflow-x: scroll">
            <h5 class="card-title">Daftar Artikel</h5>
            <table id="articles-data-table" class="table table-striped">
                <thead>
                <tr>
                    <th>Judul Artikel</th>
                    <th>Kategori</th>
                    <th>Bebas Akses</th>
                    <th>Penulis</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>Judul Artikel</th>
                    <th>Kategori</th>
                    <th>Bebas Akses</th>
                    <th>Penulis</th>
                    <th>Action</th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@push('customjs')
    <script>
        $(document).ready(function () {
            let table = $('#articles-data-table').DataTable({
                processing : true,
                serverSide : true,
                ajax : {
                    url : '{{ route('admin.article.get-articles') }}',
                    type : 'GET'
                },
                columns : [
                    {
                        data : 'title'
                    },
                    {
                        data : 'name'
                    },
                    {
                        data : 'is_locked',
                        orderable : false,
                        render : function (t) {
                            return t == 1 ? "Semua" : "Hanya Member"
                        }
                    },
                    {
                        data : 'author'
                    },
                    {
                        class : 'text-center',
                        data : 'id',
                        orderable: false,
                        defaultContent : '',
                        render : function (t) {
                            let edit = `<a class="btn btn-outline-secondary" href="{{ route('admin.article.edit', ['article' => '%%id%%']) }}"><i class="bi bi-pencil-square"></i></a>`
                            edit = edit.replace('%%id%%', t)
                            return edit;
                        }
                    }
                ]
            })
        })
    </script>
@endpush