routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');


Route::middleware('guest')->group(function () {

    Route::get('login', function () {
        return view('login');
    })->name('login');

    Route::post('login', [\App\Http\Controllers\LoginController::class, 'authenticate'])->name('login.authenticate');

});

Route::middleware('auth')->group(function () {
    Route::post('logout', [\App\Http\Controllers\LoginController::class, 'destroy'])->name('logout');
});

Route::get('categories/{slug}', [\App\Http\Controllers\CategoryController::class, 'show'])->name('article.index');

Route::get('articles/{article}', [\App\Http\Controllers\ArticleController::class, 'show'])->name('article.show');

Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::middleware('author')->group(function () {
        Route::get('dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        Route::prefix('articles')->name('article.')->group(function () {
            Route::get('', [\App\Http\Controllers\ArticleController::class, 'index'])->name('index');
            Route::get('create', [\App\Http\Controllers\ArticleController::class, 'create'])->name('create');
            Route::get('get-articles', [\App\Http\Controllers\ArticleController::class, 'getArticles'])->name('get-articles');
            Route::get('{article}/edit', [\App\Http\Controllers\ArticleController::class, 'edit'])->name('edit');
            Route::post('', [\App\Http\Controllers\ArticleController::class, 'store'])->name('store');
            Route::post('{article}/update', [\App\Http\Controllers\ArticleController::class, 'update'])->name('update');
            Route::post('{article}/destroy', [\App\Http\Controllers\ArticleController::class, 'destroy'])->name('destroy');
        });
    });

    Route::middleware('admin')->group(function () {
        Route::prefix('users')->name('user.')->group(function () {
            Route::get('', [\App\Http\Controllers\UserController::class, 'index'])->name('index');
            Route::get('create', [\App\Http\Controllers\UserController::class, 'create'])->name('create');
            Route::get('get-users', [\App\Http\Controllers\UserController::class, 'getUsers'])->name('get-users');
            Route::post('', [\App\Http\Controllers\UserController::class, 'store'])->name('store');
        });
    });
});

Route::prefix('profiles')->middleware(['auth', 'owner'])->name('profile.')->group(function () {
    Route::get('{user}', [\App\Http\Controllers\ProfileController::class, 'show'])->name('show');
    Route::post('{user}/update-profile-data', [\App\Http\Controllers\ProfileController::class, 'updateProfileData'])->name('update-profile-data');
    Route::post('{user}/update-profile-image', [\App\Http\Controllers\ProfileController::class, 'updateProfileImage'])->name('update-profile-image');
    Route::post('{user}/delete-profile-image', [\App\Http\Controllers\ProfileController::class, 'deleteProfileImage'])->name('delete-profile-image');
    Route::post('{user}/change-password', [\App\Http\Controllers\ProfileController::class, 'changePassword'])->name('change-password');
});

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Arirang Academy 2023</title>
    <meta content="Program dan pelatihan kursus bahasa Korea Arirang merupakan program kursus dan pelatihan untuk menghasilkan lulusan yang terampil bahasa Korea baik lisan maupun tulisan untuk berbagai tujuan dan berbagai konteks yang sesuai dengan kompetensi masing-masing level. Dan menjadi sarana agar dapat bekerja di Korea, bekerja di perusahaan Korea yang ada di Indonesia." name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ asset('assets/img/favicon.png') }}" rel="icon">
    <link href="{{ asset('assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ asset('assets/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/aos/aos.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet">
</head>
<body>
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

        <a href="{{ route('home') }}" class="logo d-flex align-items-center me-auto me-lg-0">
            <h1>Arirang <span>Academy</span></h1>
        </a>

        <nav id="navbar" class="navbar flex-row justify-content-between">
            <ul>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#home">Home</a></li>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#greeting">Greeting</a></li>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#about">About Us</a></li>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#picture">Picture</a></li>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#pengajar">Pengajar</a></li>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#program">Program</a></li>
                <li><a href="{{ Route::currentRouteName() !== 'home' ? route('home') : '' }}#contact">Contact</a></li>
                @auth()
                    @if(Auth::user()->role == 'ADMIN' || Auth::user()->role == 'PENULIS')
                        <li><a href="{{ route('admin.dashboard') }}" class="btn text-bg-dark bg-gradient py-2 px-3">Dashboard</a></li>
                    @elseif(Auth::user()->role = 'MEMBER')
                        <li><a href="{{ route('profile.show', ['user' => Auth::id()]) }}" class="btn text-bg-dark bg-gradient py-2 px-3">Profile</a></li>
                    @endif
                @endauth
                @guest()
                    <li><a href="{{ route('login') }}" class="btn text-bg-dark bg-gradient py-2 px-3">Login</a></li>
                @endguest
{{--                <li><a href="register.html" target="_blank" class="btn text-bg-primary bg-gradient py-2 px-3">Register</a></li>--}}

            </ul>
        </nav>


        <subnav id="subnav" class="subnav">
            <div id="sub-navigation-bar" class="card fixed-top" style="margin-top: 75px;">
                <div class="card-header"
                     style="color: var(--bs-card-bg);border-radius: 0;background: var(--bs-card-bg);">
                    <ul class="nav flex-row justify-content-center">
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" aria-expanded="true" data-bs-toggle="dropdown" href="#">Bahasa Korea</a>
                            <ul class="dropdown-menu" data-bs-popper="none">
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'video-kelas-bahasa-korea']) }}">Video kelas Bahasa Korea</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'idiom-korea']) }}">Idiom Korea</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'tata-bahasa']) }}">Tata Bahasa</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" aria-expanded="true" data-bs-toggle="dropdown" href="#">Kuliah di Korea</a>
                            <ul class="dropdown-menu" data-bs-popper="none">
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'perkuliahan']) }}">Perkuliahan&nbsp;</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'universitas-di-korea']) }}">Univeristas di Korea</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'beasiswa']) }}">Beasiswa</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" aria-expanded="true" data-bs-toggle="dropdown" href="#">Hallyu</a>
                            <ul class="dropdown-menu" data-bs-popper="none">
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'k-pop-k-drama']) }}">K-POP &amp; K-Drama</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'makanan-korea']) }}">Makanan Korea</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'budaya-tradisional']) }}">Budaya Tradisional</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'travelling']) }}">Travelling</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" aria-expanded="true" data-bs-toggle="dropdown" href="#">Koresponden</a>
                            <ul class="dropdown-menu" data-bs-popper="none">
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'pengumuman']) }}">Pengumuman</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'qna-sharing']) }}">QnA Sharing</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle nav-link" aria-expanded="true" data-bs-toggle="dropdown" href="#">Partisipasi</a>
                            <ul class="dropdown-menu" data-bs-popper="none">
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'berita-terkini']) }}">Berita Terkini</a></li>
                                <li><a class="dropdown-item" href="{{ route('article.index', ['slug' => 'kumpulan-cerita']) }}">Kumpulan Cerita</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </subnav>

        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
</header><!-- End Header -->

@yield('banner')

<main id="main">
    @yield('content')

    <footer class="text-center bg-dark">
        <div class="container text-white py-4 py-lg-5">
            <p class="text-muted mb-0">Copyright © Arirang Academy 2023</p>
        </div>
    </footer>

</main><!-- End #main -->

<!-- ======= Footer ======= -->
<!-- End Footer -->



<!-- <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>
<div id="preloader"></div> -->

<a href="https://wa.link/vz9brx" class="float-wa" target="_blank">
    <i class="bi bi-whatsapp"></i>
</a>
<script src="https://code.jquery.com/jquery-3.7.0.min.js"
        integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
        crossorigin="anonymous"></script>
<!-- Vendor JS Files -->


<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/vendor/aos/aos.js') }}"></script>
<script src="{{ asset('assets/vendor/glightbox/js/glightbox.min.js') }}"></script>
<script src="{{ asset('assets/vendor/purecounter/purecounter_vanilla.js') }}"></script>
<script src="{{ asset('assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ asset('assets/vendor/php-email-form/validate.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ asset('assets/js/main.js') }}"></script>


<script>
    function resizeMargin () {
        let reference = document.querySelector('#sub-navigation-bar')
        let referenceHeight = reference.offsetHeight;

        let body = document.querySelector('main#main')
        let marginTopValue = referenceHeight + "px";
        body.style.marginTop = marginTopValue
    }

    window.addEventListener('DOMContentLoaded', resizeMargin);
    window.addEventListener('resize', resizeMargin)
</script>
</body>
</html>

resources/views/login.blade.php
@extends('app')

@section('content')
    <section class="clean-block clean-form dark section-bg">
        <div class="container">
            <div class="block-heading" style="color: white;">
                <h1><b>Login</b></h1>
                <h6><b>Halo yeorobun!</b></h6>
                <h6><b>Silahkan login untuk langsung meluncur ke halaman Arirang Korean Course</b></h6>
            </div>
            <form action="{{ route('login.authenticate') }}" method="POST">
                @csrf
{{--                <p>Belum Punya Akun? <b><a id="btn-login-page" href="register.html">Register</a></b></p>--}}
                <div class="mb-3">
                    <label class="form-label" for="email">Email</label>
                    <input class="form-control item" type="email" id="email" name="email">
                </div>
                <div class="mb-3">
                    <label class="form-label" for="password">Password</label>
                    <input class="form-control" type="password" id="password" name="password">
                </div>
                <div class="mb-3">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="checkbox">
                        <label class="form-check-label" for="checkbox">Remember me</label>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Log In</button>
            </form>
        </div>
    </section>
@endsection