routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');


Route::middleware('guest')->group(function () {

    Route::get('login', function () {
        return view('login');
    })->name('login');

    Route::post('login', [\App\Http\Controllers\LoginController::class, 'authenticate'])->name('login.authenticate');

});

Route::middleware('auth')->group(function () {
    Route::post('logout', [\App\Http\Controllers\LoginController::class, 'destroy'])->name('logout');
});

Route::get('categories/{slug}', [\App\Http\Controllers\CategoryController::class, 'show'])->name('article.index');

Route::get('articles/{article}', [\App\Http\Controllers\ArticleController::class, 'show'])->name('article.show');

Route::prefix('admin')->middleware('auth')->name('admin.')->group(function () {
    Route::middleware('author')->group(function () {
        Route::get('dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');

        Route::prefix('articles')->name('article.')->group(function () {
            Route::get('', [\App\Http\Controllers\ArticleController::class, 'index'])->name('index');
            Route::get('create', [\App\Http\Controllers\ArticleController::class, 'create'])->name('create');
            Route::get('get-articles', [\App\Http\Controllers\ArticleController::class, 'getArticles'])->name('get-articles');
            Route::get('{article}/edit', [\App\Http\Controllers\ArticleController::class, 'edit'])->name('edit');
            Route::post('', [\App\Http\Controllers\ArticleController::class, 'store'])->name('store');
            Route::post('{article}/update', [\App\Http\Controllers\ArticleController::class, 'update'])->name('update');
            Route::post('{article}/destroy', [\App\Http\Controllers\ArticleController::class, 'destroy'])->name('destroy');
        });
    });

    Route::middleware('admin')->group(function () {
        Route::prefix('users')->name('user.')->group(function () {
            Route::get('', [\App\Http\Controllers\UserController::class, 'index'])->name('index');
            Route::get('create', [\App\Http\Controllers\UserController::class, 'create'])->name('create');
            Route::get('get-users', [\App\Http\Controllers\UserController::class, 'getUsers'])->name('get-users');
            Route::post('', [\App\Http\Controllers\UserController::class, 'store'])->name('store');
        });
    });
});

Route::prefix('profiles')->middleware(['auth', 'owner'])->name('profile.')->group(function () {
    Route::get('{user}', [\App\Http\Controllers\ProfileController::class, 'show'])->name('show');
    Route::post('{user}/update-profile-data', [\App\Http\Controllers\ProfileController::class, 'updateProfileData'])->name('update-profile-data');
    Route::post('{user}/update-profile-image', [\App\Http\Controllers\ProfileController::class, 'updateProfileImage'])->name('update-profile-image');
    Route::post('{user}/delete-profile-image', [\App\Http\Controllers\ProfileController::class, 'deleteProfileImage'])->name('delete-profile-image');
    Route::post('{user}/change-password', [\App\Http\Controllers\ProfileController::class, 'changePassword'])->name('change-password');
});

resources/views/admin/dashboard.blade.php
@extends('admin.layout')

@section('content')
    <div class="pagetitle">
        <h1>Dashboard</h1>
    </div><!-- End Page Title -->

    <section class="section dashboard">
        <div class="row">
            <div class="col-xxl-4 col-md-6">
                <div class="card info-card sales-card">
                    <div class="card-body">
                        <h5 class="card-title">Jumlah Member</h5>
                        <div class="d-flex align-items-center">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                <i class="bi bi-people"></i>
                            </div>
                            <div class="ps-3">
                                <h6>{{ $memberCount }}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xxl-4 col-md-6">
                <div class="card info-card sales-card">
                    <div class="card-body">
                        <h5 class="card-title">Jumlah Penulis</h5>
                        <div class="d-flex align-items-center">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                <i class="bi bi-person-gear"></i>
                            </div>
                            <div class="ps-3">
                                <h6>{{ $authorCount }}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xxl-4 col-md-6">
                <div class="card info-card sales-card">
                    <div class="card-body">
                        <h5 class="card-title">Jumlah Artikel</h5>
                        <div class="d-flex align-items-center">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                <i class="bi bi-files"></i>
                            </div>
                            <div class="ps-3">
                                <h6>{{ $articlesCount }}</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col ">
                <!-- News & Updates Traffic -->
                <div class="card">
                    <div class="card-body pb-0">
                        <h5 class="card-title">Artikel Terbaru</h5>

                        <div class="news">
                            @foreach($recentArticles as $article)
                                <div class="post-item clearfix">
                                    <img src="{{ asset($article->cover_image) }}" alt="">
                                    <h4><a href="{{ route('article.show', ['article' => $article->id]) }}">{{ $article->title }} <span class="text-muted">({{ \Illuminate\Support\Carbon::parse($article->created_at)->toFormattedDateString() }})</span></a></h4>
                                    <div class="row mb-3">
                                        <div>
                                            <a href="{{ route('admin.article.edit', ['article' => $article->id]) }}" class="btn btn-sm btn-outline-secondary"><i class="bi bi-pencil-square"></i> Edit</a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div><!-- End sidebar recent posts-->
                    </div>
                </div><!-- End News & Updates -->
            </div>


        </div>
    </section>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard Admin</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{{ asset('assets/img/favicon.png') }}" rel="icon">
    <link href="{{ asset('assets/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/quill/quill.snow.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/quill/quill.bubble.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/vendor/simple-datatables/style.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    <!-- CropperJS -->
    <link rel="stylesheet" href="{{asset('assets/css/cropper.min.css')}}">

    <!-- Template Main CSS File -->
    <link href="{{ asset('assets/css/style-admin.css') }}" rel="stylesheet">
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="{{ route('home') }}" class="logo d-flex align-items-center">
            <span class="d-none d-lg-block">Arirang Academy</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    @if(Auth::user()->profile_image != null && File::exists(public_path(Auth::user()->profile_image)))
                        <img src="{{ asset(Auth::user()->profile_image) }}" alt="Profile" class="rounded-circle">
                    @else
                        <img src="https://ui-avatars.com/api/?name={{ Auth::user()->name }}" alt="Profile" class="rounded-circle">
                    @endif
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ Auth::user()->name }}</span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{ Auth::user()->name }}</h6>
                        <span>{{ ucwords(strtolower(Auth::user()->role)) }}</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{{ route('profile.show', ['user' => Auth::id()]) }}">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li id="sign-out-button">
                        <form action="{{ route('logout') }}" method="POST" id="logout">
                            @csrf
                            <a class="dropdown-item d-flex align-items-center" href="#">
                                <i class="bi bi-box-arrow-right"></i>
                                <span >Sign Out</span>
                            </a>
                        </form>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        @if(Auth::user()->role == 'PENULIS' || Auth::user()->role == 'ADMIN')

            <li class="nav-item ">
                <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.dashboard') ? 'active' : "" }}" href="{{ route('admin.dashboard') }}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">
                <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.article.') ? 'active' : "collapsed" }}" data-bs-target="#articles-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Artikel</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="articles-nav" class="nav-content collapse {{ str_contains(Route::currentRouteName(), 'admin.article.') ? 'show' : "" }}" data-bs-parent="#sidebar-nav">
                    <li>
                        <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.article.index') ? 'active' : "" }}" href="{{ route('admin.article.index') }}">
                            <i class="bi bi-circle"></i><span>Daftar Artikel</span>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.article.create') ? 'active' : "" }}" href="{{ route('admin.article.create') }}">
                            <i class="bi bi-circle"></i><span>Menulis Artikel</span>
                        </a>
                    </li>
                </ul>
            </li><!-- End Artikel Nav -->

            @if(Auth::user()->role == 'ADMIN')
                <li class="nav-item">
                    <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.user.') ? 'active' : "collapsed" }}" data-bs-target="#users-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-people"></i><span>Pengguna</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="users-nav" class="nav-content collapse {{ str_contains(Route::currentRouteName(), 'admin.user.') ? 'show' : "" }}" data-bs-parent="#sidebar-nav">
                        <li>
                            <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.user.index') ? 'active' : "" }}" href="{{ route('admin.user.index') }}">
                                <i class="bi bi-circle"></i><span>Daftar Pengguna</span>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link {{ str_contains(Route::currentRouteName(), 'admin.user.create') ? 'active' : "" }}" href="{{ route('admin.user.create') }}">
                                <i class="bi bi-circle"></i><span>Tambah Pengguna</span>
                            </a>
                        </li>
                    </ul>
                </li><!-- End Artikel Nav -->
            @endif
        @endif

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link {{ str_contains(Route::currentRouteName(), 'profile') ? 'active' : "" }}" href="{{ route('profile.show', ['user' => Auth::id()]) }}">
                <i class="bi bi-person"></i>
                <span>Profile</span>
            </a>
        </li><!-- End Profile Page Nav -->

    </ul>

</aside><!-- End Sidebar-->

<main id="main" class="main">

    @yield('content')

</main><!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Arirang Academy</span></strong>. 2023
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>

<!-- Vendor JS Files -->
<script src="{{ asset('assets/vendor/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/vendor/chart.js/chart.umd.js') }}"></script>
<script src="{{ asset('assets/vendor/echarts/echarts.min.js') }}"></script>
<script src="{{ asset('assets/vendor/quill/quill.min.js') }}"></script>
<script src="{{ asset('assets/vendor/simple-datatables/simple-datatables.js') }}"></script>
<script src="{{ asset('assets/vendor/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('assets/vendor/php-email-form/validate.js') }}"></script>

<!-- Template Main JS File -->
<script src="{{ asset('assets/js/main-admin.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script>
    const Toast = Swal.mixin({
        toast: true,
        position: 'bottom-end',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
    })
</script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/38.0.1/classic/ckeditor.js"></script>
<!-- CropperJS -->
<script src="{{asset('assets/js/cropper.min.js')}}"></script>

<script>
    $(document).ready(function () {
        $('#sign-out-button').on('click', function (e) {
            e.preventDefault()
            $('form#logout').submit();
        })
    })
</script>

@stack('customjs')

</body>

</html>